### ISSUE TITLE
mount failure on ppc64le with NVMe boot drives

### ISSUE THREAD

**Issue by manojnkumar** [coreos/coreos-installer#143] opened 2020-01-17 14:17 UTC
Running into this issue on a brand-new ppc64le system, that boots RHEL 8 fine.  The boot disk is NVMe.

```
[  104.638649] coreos-installer[2860]: Wiping /dev/nvme0n1
[  104.657365] coreos-installer[2860]: /dev/nvme0n1: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa
[  104.657495] coreos-installer[2860]: Writing disk image
[  104.658765] coreos-installer[2860]: 2+0 records in
[  104.658841] coreos-installer[2860]: 2+0 records out
[  104.658917] coreos-installer[2860]: 2 bytes copied, 4.088e-05 s, 48.9 kB/s
[  220.262600] coreos-installer[2860]: Waiting for udev
[  220.280953] coreos-installer[2860]: Embedding provided Ignition config
[  220.290255] coreos-installer[2860]: mount: /mnt/boot_partition: no filesystem type specified.

...

[  250.413009] coreos-installer[2860]: failed mounting boot partition
Usage: /usr/libexec/coreos-installer [options]
Options:
    -d DEVICE   Install to the given device, alternatively specify
                coreos.inst.install_dev on the kcmdline.
    -i IGNITION The URL (or path) to the given Ignition config,
                alternatively specify coreos.inst.ignition_url on the
                kcmdline.
    -b BASEURL  The URL to the image, alternatively specify
                coreos.inst.image_url on the kcmdline.
    -h          This.

This tool installs CoreOS style disk images on a block device.
```

@cgwalters has recommended that I add:

```
--- a/coreos-installer
+++ b/coreos-installer
@@ -323,6 +323,7 @@ mount_boot_partition() {
     while true
     do
         output=$(lsblk "${DEST_DEV}" --output NAME,LABEL,UUID --pairs | grep 'LABEL="boot"')
+        echo ${output}
         eval $(echo $output | tr ' ' '\n' | tail -n 1)
         mount "/dev/disk/by-uuid/${UUID}" "$boot_partition"
         RETCODE=$?
```

**Comment by manojnkumar** [comment] 2020-01-17 15:33
The installation method used was:

https://gitlab.cee.redhat.com/multi-arch/openshift-upi-playbooks

Edit to point to the rhcos image: rhcos-43ppc64ledevel.81.202001150649.0
And run the playbook:
```
ansible-playbook -i inventory playbooks/main.yml
```

**Comment by manojnkumar** [comment] 2020-02-20 20:41
coreos-installer works fine on the same system with SATA ssd.

**Comment by manojnkumar** [comment] 2020-02-26 16:24
The NVMe drives were set to 4k sectors. When I reformatted the drives to 512b sectors, the installer proceeded to completion.

i.e. This issue is the same as: https://github.com/coreos/fedora-coreos-tracker/issues/385

**Comment by bgilbert** [comment] 2020-02-26 16:37
Great, thanks for tracking this down.  I'll close as a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/385.

**Closed by bgilbert** 2020-02-26 16:37 UTC
Labels: legacy
