### ISSUE TITLE
/dev/sda device is in use in bare-metal server

### ISSUE THREAD

**Issue by majorinche** [coreos/coreos-installer#261] opened 2020-06-02 11:30 UTC
try to install fcos by pxe in bare-metal server, but meet the error, like

_checking for exclusive access to /dev/sda
caused by: couldn't reread partition table: device is in use_

other information:
pxelinux.cfg is:
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL fedora-coreos-31.20200505.3.0-live-kernel-x86_64
    APPEND ip=dhcp rd.neednet=1 initrd=fedora-coreos-31.20200505.3.0-live-initramfs.x86_64.img coreos.inst=yes coreos.inst.ignition_url=http://10.30.0.109/example.ign coreos.inst.image_url=http://10.30.0.109/fedora-coreos-31.20200505.3.0-metal.x86_64.raw.xz coreos.inst.install_dev=/dev/sda coreos.inst.insecure=yes
IPAPPEND 2

**Comment by 2goobers** [comment] 2020-06-17 02:40
Same issue with iso boot live image.
Both fedora-coreos-31.20200517.3.0-live.x86_64.iso &
fedora-coreos-32.20200601.3.0-live.x86_64.iso
using CLI to initiate, and kernel line args

**Comment by jlebon** [comment] 2020-06-17 14:42
Can one of you print the full output from `coreos-installer`? Specifically, does this error happen at the end of the install or at the start?

**Comment by 2goobers** [comment] 2020-06-18 01:36
The full output I get is this:

Error: checking for exclusive access to /dev/sda
Caused by: couldn't reread partition table: device is in use
Caused by: EBUSY: Device or resource busy

This comes up a few seconds after:
curl -O http://X.X.X.X:8000/example.ign
sudo coreos-installer install /dev/sda -i example.ign

**Comment by bgilbert** [comment] 2020-06-18 02:06
Could you drop the `coreos.inst=yes` and `coreos.inst.image_url` arguments, boot to a prompt (easier with the ISO image), and check `/proc/mounts` and `/proc/swaps` for partitions on `/dev/sda`?  The output of `sgdisk -p /dev/sda` would also be helpful.

**Comment by 2goobers** [comment] 2020-06-18 02:49
Nothing to `/dev/sda` on `/proc/mounts`
Nothing in `/proc/swaps`

Here is `sudo sgdisk -p /dev/sda`

> Disk /dev/sda: 234441648 sectors, 111.8 GiB
> Model: KINGSTON SV300S3
> Sector size (logical/physical): 512/512 bytes
> Disk identifier (GUID): B6F22F01-F3E7-41F2-9AED-8613426CA213
> Partition table holds up to 128 entries
> Main partition table begins at sector 2 and ends at sector 33
> First usable sector is 34, last usable sector is 234441614
> Partitions will be aligned on 2048-sector boundaries
> Total free space is 2452333 sectors (1.2 GiB)
> 
> Number  Start (sector)    End (sector)  Size       Code  Name
>    1            2048         1230847   600.0 MiB   EF00  EFI System Partition
>    2         1230848         3327999   1024.0 MiB  8300
>    3         3328000       231991295   109.0 GiB   8E00

**Comment by bgilbert** [comment] 2020-06-18 04:51
> 3 3328000 231991295 109.0 GiB 8E00

Aha!  Your disk has an LVM physical volume.  What does `lvs` say?

**Comment by bgilbert** [comment] 2020-06-23 11:41
It turns out that Linux MD partitions and LVM PVs are automatically run at startup, which interferes with `coreos.inst`.

**Comment by bgilbert** [comment] 2020-06-23 15:30
Thanks for the report.  This should be fixed by https://github.com/coreos/coreos-installer/pull/276.

**Comment by MarkIannucci** [comment] 2020-06-29 13:49
@bgilbert , I'm bumping up against this as well with my bare metal install on an old laptop.  Are you aware of a workaround that I can use to get past this issue?

**Comment by bgilbert** [comment] 2020-06-29 14:02
@MarkIannucci If you're doing a one-off install, it's easiest to work around this by hand:

1. Boot the live image without any `coreos.inst` options
2. `sudo mdadm --stop /dev/mdXXX` for each `mdXXX` listed in `/proc/mdstat`
3. `sudo vgchange -an XXX` for each VG listed in `sudo vgs`
4. `curl -o config.ign <ignition_config_url>`
5. `sudo coreos-installer install <target-device> -i config.ign <other-args>`

**Closed** 2020-06-29 22:36 UTC
Labels: jira, kind/bug

**Comment by blueskyjunkie** [comment] 2024-12-28 15:10
I seem to have run into this problem with a bare metal live ISO install. The disk had an old ubuntu installation using LVM which blocked the coreos-installer run from the coreos live installer.

To enable install I had to do these commands before running coreos-installer.

```
sudo lvm lvremove ubuntu-vg
sudo lvm vgremove ubuntu-vg
```

**Comment by jlebon** [comment] 2025-01-22 18:20
@blueskyjunkie Thanks for the report. We don't have tests for this currently. Can you open a new issue?
