### ISSUE TITLE
coreos-install iso embed --no-initramfs-networking

### ISSUE THREAD

**Issue by cgwalters** [coreos/coreos-installer#164] opened 2020-02-18 17:55 UTC
For the use case of static IPs on bare metal, we have `coreos-install iso embed` to insert Ignition, but that still has an implicit requirement on DHCP.

Let's add an option to `embed` that [turns it off](https://github.com/coreos/ignition-dracut/issues/94), like:

```
$ coreos-install iso embed --no-initramfs-networking -c /path/to/config.ign /path/to/foo.iso
```

**Comment by bgilbert** [comment] 2020-02-18 21:57
This seems like a special case of a more general thing I've proposed before (though apparently I never filed a bug about it): provide an option for embedding any karg interpreted by Dracut, including the networking options generally.  It'd be easy to implement (drop a file in `/etc/cmdline.d` in the CPIO archive), but a hard distinction to make to the user, who can't be expected to know which kargs are implemented where.

Thoughts?

**Comment by cgwalters** [comment] 2020-02-19 00:01
Definitely related, although this gets into a few interesting details - among them that there's not really a standard way to *remove* a kernel argument, which is relevant here for disabling networking that is enabled by default.

**Comment by jlebon** [comment] 2020-02-19 19:02
We wouldn't need to remove a karg I think, just append `rd.neednet=0`. And hmm... actually, it'd probably work today to do `coreos-installer install --firstboot-args rd.neednet=0`?

**Comment by bgilbert** [comment] 2020-02-20 02:42
I'd guess `rd.neednet=0` would work.  The issue is the live ISO boot, not the boot of the installed system, so `--firstboot-args` is too late.

**Comment by cgwalters** [comment] 2020-02-20 14:11
I guess we could generalize this to `--initialboot-args`.  I agree that appending `rd.neednet=0` likely works in practice and would be fine, but it just feels less clean than actually removing the argument.

**Comment by jlebon** [comment] 2020-03-31 15:46
This is part of the more generic conditional networking issue: https://github.com/coreos/fedora-coreos-tracker/issues/443.

**Comment by dustymabe** [comment] 2020-04-03 22:07
> For the use case of static IPs on bare metal, we have `coreos-install iso embed` to insert Ignition, but that still has an implicit requirement on DHCP.

After https://github.com/coreos/fedora-coreos-config/pull/326 the Live ISO image no longer requires DHCP.

**Comment by jlebon** [comment] 2021-07-06 12:57
The ISO (as with all the other artifacts) no longer default to initramfs networking. So closing this.

**Closed by jlebon** 2021-07-06 12:57 UTC
