### ISSUE TITLE
https://builds.coreos.fedoraproject.org/streams/stable.json access denied

### ISSUE THREAD

**Issue by gabx** [coreos/coreos-installer#106] opened 2019-12-04 12:22 UTC
# Bug #

## Host Operating System Version ##
arch linux

## coreos-installer Version ##
```
% coreos-installer --version                                 
coreos-installer 0.1.0
```

## Expected Behavior ##
`$ coreos-installer list-stream` output a list Fedora CoreOS images available for download 

## Actual Behavior ##
```
% coreos-installer list-stream
Error: stream metadata fetch from https://builds.coreos.fedoraproject.org/streams/stable.json failed: 403 Forbidden
```

## Reproduction Steps ##

  1. ...
  2. ...

## Other Information ##
```
% curl https://builds.coreos.fedoraproject.org/streams/stable.json 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>BCBD925739E2F147</RequestId><HostId>pARkJlDe27XakJaB7P6nOolcR4ifIjebVUI2j69BIzLuPs9QZeD+k/SALiOE7wrIbN5c9hD5cbw=</HostId></Error>% 
```

**Comment by lucab** [comment] 2019-12-04 13:33
Thanks for the report.
The error you are seeing is because we default the installer to the `stable` stream (for future-proofing, I think) but we haven't yet published any release in that stream. It should start working as soon as we start publishing the first `stable` release.

Anyway, you can select the relevant stream with `-s`. At the moment, `-s testing` should work already and consume the `testing` stream.

**Comment by lucab** [comment] 2019-12-04 13:36
@jlebon @dustymabe do we maybe want to publish an empty stream metadata for `stable`, for the time being? That should silence the error at hand, but it won't still list anything useful for some time.

**Comment by dustymabe** [comment] 2019-12-04 15:44
> @jlebon @dustymabe do we maybe want to publish an empty stream metadata for `stable`, for the time being? That should silence the error at hand, but it won't still list anything useful for some time.

Sounds good to me. Either that or have the installer default to testing for now.

**Comment by lucab** [comment] 2019-12-04 16:26
Unfortunately it takes a painful amount of time to go from a commit here to the binary appearing in FCOS. I'd rather not go through (at least two) cycles of flipping the hard-coded default.

**Comment by lucab** [comment] 2020-01-14 09:32
Stream metadata for `stable` is now up, URL confirmed working. Closing this.

**Closed by lucab** 2020-01-14 09:32 UTC
