### ISSUE TITLE
Error : "end of file before message length reached"

### ISSUE THREAD

**Issue by fclerg** [coreos/coreos-installer#199] opened 2020-03-27 01:59 UTC
# Bug #

## Host Operating System Version ##
Proxmox 5.2-12

## Target Operating System Version ##
fedora-coreos-31.20200210.3.0

## coreos-installer Version ##
coreos-installer 0.1.2

## Expected Behavior ##
Successful installation of CoreOS

## Actual Behavior ##
<img width="867" alt="coreos-installer-error" src="https://user-images.githubusercontent.com/29798784/77686663-31879200-6f95-11ea-99f2-263e50bd643b.png">

The relevant part seems to be :
`Caused by: end of file before message length reached`

## Reproduction Steps ##
PXE boot. Here is my iPXE config (it is provided by Matchbox to match a configuration with a machine):
```
	"boot": {
		"kernel": "http://10.20.30.100:8000/image/fedora-coreos-31.20200210.3.0-live-kernel-x86_64",
		"initrd": [
			"http://10.20.30.100:8000/image/fedora-coreos-31.20200210.3.0-live-initramfs.x86_64.img"
		],
		"args": [
			"ip=dhcp",
			"rd.neednet=1",
			"initrd=fedora-coreos-31.20200210.3.0-live-initramfs.x86_64.img",
			"coreos.inst.image_url=http://10.20.30.100:8000/image/fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz",
			"coreos.inst.ignition_url=http://matchbox.yuzu.local:8080/ignition?uuid=${uuid}\u0026mac=${mac:hexhyp}",
			"coreos.inst.install_dev=sda",
                        "coreos.inst.insecure=yes",
                        "random.trust_cpu=on",
			"console=tty0",
                        "systemd.journald.max_level_console=debug"
		]
	}
```
## Other Information ##
After it fails I can access the emergency mode for maintenance.
From there I could confirm that the guest gets its IP config with DHCP and that it has access to the internet.
I didn't find anything obvious about the failure. I am not sure where to look at, based on this "_end of file before message length reached_" error message.

The image I use is _fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz_.
I use a copy of the image in a local web repo and I can confirm its signature and integrity :
```
# gpg --verify fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz.sig  fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz
gpg: Signature made Mon Feb 24 18:03:55 2020 UTC using RSA key ID 3C3359C4
gpg: Good signature from "Fedora (31) <fedora-31-primary@fedoraproject.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D22 D586 7F2A 4236 474B  F7B8 50CB 390B 3C33 59C4
#
```

```
# curl -s https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200210.3.0/x86_64/meta.json \
>   | jq -r '.images.metal | select(.path=="fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz") | .sha256'
8ed20e48375ea2c0c09dace2a06d366d80990f97f2a79757dbc81078424725c6
# sha256sum  fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz
8ed20e48375ea2c0c09dace2a06d366d80990f97f2a79757dbc81078424725c6  fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz
#
```

**Comment by dustymabe** [comment] 2020-03-30 00:59
duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/439 where we've got some conversations going on already so let's close this.

**Closed by dustymabe** 2020-03-30 00:59 UTC
