### ISSUE TITLE
inappropriate ioctl for device in vmware vm

### ISSUE THREAD

**Issue by majorinche** [coreos/coreos-installer#260] opened 2020-06-02 08:23 UTC
using coreos-installer to install fcos with pxe in vmware env

installation can be ok, but after reboot, it will report this issue:

Emergency.service: failed at step STDIN spawning /bin/dracut-emergency: Inappropriate ioctl for device

version:
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL fedora-coreos-31.20200505.3.0-live-kernel-x86_64
    APPEND ip=dhcp rd.neednet=1 initrd=fedora-coreos-31.20200505.3.0-live-initramfs.x86_64.img coreos.inst=yes coreos.inst.ignition_url=http://10.30.0.109/worker.ign coreos.inst.image_url=http://10.30.0.109/fedora-coreos-31.20200505.3.0-metal.x86_64.raw.xz coreos.inst.install_dev=/dev/sda coreos.inst.insecure=yes
IPAPPEND 2

**Comment by lucab** [comment] 2020-06-02 11:55
That error means there are some boot failures.
If you set up your system console properly, you'll get an emergency console for further troubleshooting.
See https://docs.fedoraproject.org/en-US/fedora-coreos/emergency-shell/ for further details.

**Comment by majorinche** [comment] 2020-06-03 02:09
try to reboot to go emergency, but after reboot, vm will re-install os automatically, and can not get into emergency mode
i try use other images, like: fedora-coreos-31.20200505.3.0-vmware.x86_64.ova or fedora-coreos-31.20200505.3.0-live.x86_64.iso within pxe, but new error will come out

Couldn’t find any partitions on /dev/sda
Clearing partition table
Error: install failed

**Comment by majorinche** [comment] 2020-06-03 12:19
it seems the ign file cause this error, i try to analysis the ign file with ignition-validate, find many errors

[root@ip-172-31-8-20 ~]# podman run --rm -i quay.io/coreos/ignition-validate - < bootstrap.ign
error at $.storage.files.49, line 1 col 110199: duplicate entry defined
error at $.storage.files.50, line 1 col 112087: duplicate entry defined
warning at $.networkd, line 1 col 81: Unused key networkd
warning at $.storage.files.0.mode, line 1 col 1650: Unused key filesystem
warning at $.storage.files.1.mode, line 1 col 2102: Unused key filesystem
warning at $.storage.files.2.mode, line 1 col 2513: Unused key filesystem
warning at $.storage.files.3.mode, line 1 col 5346: Unused key filesystem
warning at $.storage.files.4.mode, line 1 col 5515: Unused key filesystem



and this ign file is generated by "openshift-install create ignition-configs" while i'm trying to install FCOS for openshift/okd 4.4
the ign version generated here is: 2.2.0
{"ignition":{"config":{},"security":{"tls":{}},"timeouts":{},"version":"2.2.0"}

but the current ignition version seems be: 3.0.0
[root@ocpadmin ~]# cat example.ign 
{"ignition": {"config": {"replace": {"source": null,"verification": {}}},"security": {"tls": {}},"timeouts": {},version": "3.0.0"},

**Comment by bgilbert** [comment] 2020-06-26 10:36
Closing as duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/516.

**Closed by bgilbert** 2020-06-26 10:36 UTC
